# Generated by Django 4.2.30 on 2026-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('interest', models.CharField(choices=[('blej', 'Dua të blej'), ('shes', 'Dua të shes'), ('qira-kerkoje', 'Kërkoj qira'), ('qira-ofroj', 'Ofroj qira'), ('investim', 'Investim')], default='blej', max_length=20)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('property_type', models.CharField(choices=[('banese', 'Banesë'), ('penthouse', 'Penthouse'), ('vile', 'Vilë'), ('zyre', 'Zyre'), ('lokal', 'Lokal'), ('toke', 'Tokë')], max_length=20)),
                ('property_status', models.CharField(choices=[('shitje', 'Shitje'), ('qira', 'Qira')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('shitje', 'Shitje'), ('qira', 'Qira')], db_index=True, max_length=20)),
                ('type', models.CharField(choices=[('banese', 'Banesë'), ('penthouse', 'Penthouse'), ('vile', 'Vilë'), ('zyre', 'Zyre'), ('lokal', 'Lokal'), ('toke', 'Tokë')], db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('neighborhood', models.CharField(db_index=True, max_length=200)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('area', models.PositiveIntegerField(help_text='Area in m²')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('has_ownership_doc', models.BooleanField(default=True, help_text='Fletë poseduese')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('language', models.CharField(choices=[('sq', 'Shqip'), ('en', 'English'), ('de', 'Deutsch')], default='sq', max_length=2)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
