# Generated by Django 4.2.30 on 2026-05-10 18:40
# Hand-edited to safely backfill slug values before applying the unique constraint.

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Property = apps.get_model("core", "Property")
    for prop in Property.objects.all():
        if prop.slug:
            continue
        base = slugify(f"{prop.title}-{prop.neighborhood}")[:200] or "prona"
        prop.slug = f"{base}-{prop.pk}"
        prop.save(update_fields=["slug"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, help_text="Përshkrim i plotë i pronës — kati, gjendja, veçoritë"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_published",
            field=models.BooleanField(db_index=True, default=True, help_text="Çpublikuar = nuk shfaqet në faqe por mbetet në admin"),
        ),
        # 1) Add slug as a plain CharField first so existing rows can hold empty strings.
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=240),
            preserve_default=False,
        ),
        # 2) Backfill unique slugs from title+neighborhood+pk for every existing row.
        migrations.RunPython(backfill_slugs, noop_reverse),
        # 3) Promote to a real SlugField with the unique constraint now that data is clean.
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
    ]
