# Generated by Django 4.2.30 on 2026-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_description_property_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in m²', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
