# Generated by Django 4.2.30 on 2026-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_property_area_alter_property_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrequest',
            name='property_type',
            field=models.CharField(choices=[('banese', 'Banesë'), ('shtepi', 'Shtëpi'), ('penthouse', 'Penthouse'), ('vile', 'Vilë'), ('zyre', 'Zyre'), ('objekt', 'Objekt'), ('lokal', 'Lokal'), ('biznes', 'Biznes'), ('depo', 'Depo'), ('toke', 'Tokë')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('banese', 'Banesë'), ('shtepi', 'Shtëpi'), ('penthouse', 'Penthouse'), ('vile', 'Vilë'), ('zyre', 'Zyre'), ('objekt', 'Objekt'), ('lokal', 'Lokal'), ('biznes', 'Biznes'), ('depo', 'Depo'), ('toke', 'Tokë')], db_index=True, max_length=20),
        ),
    ]
