# Generated by Django 5.2.15 on 2026-06-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listingrequest_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
